export const listTopicData = [
  {
    id: 1,
    section: "house",
    name: "La casa",
    imageResource: require("./img/house.jpeg"),
    imageAlt: "La casa",
  },
  {
    id: 2,
    section: "house",
    name: "Il soggiorno",
    imageResource: require("./img/livingRoom.jpeg"),
    imageAlt: "Il soggiorno",
  },
  {
    id: 3,
    section: "house",
    name: "La cucina",
    imageResource: require("./img/kitchen.jpeg"),
    imageAlt: "La cucina",
  },
  {
    id: 4,
    section: "house",
    name: "La camera da letto",
    imageResource: require("./img/bedroom.jpeg"),
    imageAlt: "La camera da letto",
  },
  {
    id: 5,
    section: "house",
    name: "La stanza da bagno",
    imageResource: require("./img/bathroom.jpeg"),
    imageAlt: "La stanza da bagno",
  },
  {
    id: 6,
    section: "house",
    name: "La sala da pranzo",
    imageResource: require("./img/diningRoom.jpeg"),
    imageAlt: "La sala da pranzo",
  },
  {
    id: 7,
    section: "house",
    name: "La camera del bambino",
    imageResource: require("./img/nursery.jpeg"),
    imageAlt: "La camera del bambino",
  },
  {
    id: 8,
    section: "house",
    name: "Il laboratorio",
    imageResource: require("./img/workshop.jpeg"),
    imageAlt: "Il laboratorio",
  },
  {
    id: 9,
    section: "house",
    name: "Il gardino",
    imageResource: require("./img/garden.jpg"),
    imageAlt: "Il gardino",
  },
  {
    id: 10,
    section: "people",
    name: "Il Corpo",
    imageResource: require("./img/body.jpg"),
    imageAlt: "Il corpo",
  },
  {
    id: 11,
    section: "people",
    name: "La faccia",
    imageResource: require("./img/fase.png"),
    imageAlt: "La faccia",
  },
];